# Generated by Django 5.1.1 on 2024-10-16 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_usersalary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersalary',
            name='user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_info', to='account.userinfo'),
        ),
    ]
