# Generated by Django 5.0.7 on 2024-09-17 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('inventory', '0002_category_hospital_item_hospital_order_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
    ]
