# Generated by Django 5.0.7 on 2024-09-17 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('inventory', '0003_alter_order_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
    ]
