# Generated by Django 5.1.1 on 2024-10-20 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_patient_user'),
        ('inventory', '0004_alter_order_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
    ]
