# Generated by Django 5.1.1 on 2024-10-21 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_patient_user'),
        ('inventory', '0006_remove_supplier_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
        migrations.AlterField(
            model_name='item',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
