# Generated by Django 5.1.1 on 2024-10-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[(1, 'Inactive'), (2, 'Active')], max_length=10),
        ),
    ]
